---
abstract: 'Web Scraping Toolkit inspired by Scrapi'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Scraper
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  HTML::Entities: 0
  HTML::Selector::XPath: 0.03
  HTML::Tagset: 0
  HTML::TreeBuilder: 3.23
  HTML::TreeBuilder::XPath: 0.08
  HTTP::Response::Encoding: 0
  LWP::UserAgent: 0
  Scalar::Util: 0
  UNIVERSAL::require: 0
  URI: 0
  XML::XPathEngine: 0.08
  YAML: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.27
