---
abstract: 'Web Scraping Toolkit using HTML and CSS Selectors or XPath expressions'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Base: 0
  Test::More: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Scraper
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTML::Entities: 0
  HTML::Selector::XPath: 0.03
  HTML::Tagset: 0
  HTML::TreeBuilder: 3.23
  HTML::TreeBuilder::XPath: 0.08
  LWP: 5.827
  Scalar::Util: 0
  UNIVERSAL::require: 0
  URI: 0
  XML::XPathEngine: 0.08
  YAML: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/web-scraper.git
version: 0.34
