abstract: Web Scraping Toolkit inspired by Scrapi
author: Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Web-Scraper
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::Entities: 0
  HTML::Selector::XPath: 0
  HTML::Tagset: 0
  HTML::TreeBuilder::XPath: 0.08
  HTTP::Response::Encoding: 0
  LWP::UserAgent: 0
  Scalar::Util: 0
  URI: 0
  XML::XPathEngine: 0.08
  YAML: 0
version: 0.19
